project:
  type: website

website: 
  title: "Polyphonic Perspectives"
  navbar:
    left:
      - href: blog.qmd
        text: Posts
      - index.qmd
    right:
    
      - icon: github
        href: https://github.com/nikhilpmonline
        aria-label: GitHub
      - icon: mastodon
        href: https://masto.ai/@nikhilpm
        aria-label: Mastodon
      - icon: linkedin
        href: https://www.linkedin.com/in/nikhil-p-m-0196b5185/
        aria-label: Linkedin

format:
  html:
    theme:
      light: lux
      dark: darkly
    css: styles.css
    toc: true

editor: visual

